# Generated by Django 5.0.2 on 2025-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_total_amount_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена'),
        ),
    ]
