# Generated by Django 5.0.2 on 2025-06-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_options_remove_order_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
    ]
