# Generated by Django 5.0.2 on 2025-06-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orderitem_quantity_delivery_deliveryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
    ]
