# Generated by Django 5.0.2 on 2025-06-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата привоза'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=3, verbose_name='Тип движения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('source_type', models.CharField(max_length=10, verbose_name='Тип источника')),
                ('source_id', models.PositiveIntegerField(verbose_name='ID источника')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Движения товаров',
                'ordering': ['-date'],
            },
        ),
    ]
